// File picker API; Primarily generated by Claude and then modified, using https://github.com/abdelrahman-tarek-0/popups-file-dialog for inspiration

import fs from 'fs/promises'
import os from 'os'
import path from 'path'

export interface OpenFileOptions<T extends boolean> {
  /** Dialog window title */
  title?: string
  /** Directory (or file) to open the dialog in */
  startPath?: string
  /** Patterns. Use ['*'] for "all files". */
  filterPatterns?: string[]
  /** Human readable label for the filter */
  filterPatternsDescription?: string
  /** Allow selecting more than one file */
  allowMultipleSelects?: T
}

/**
 * Opens a native "open file" dialog on macOS, Windows, or Linux with zero
 * compiled dependencies — it shells out to a binary every desktop OS already
 * ships (osascript, PowerShell, zenity/kdialog).
 * @param options Options for the file prompt
 * @returns       The paths of the files selected
 */
export async function openFile<T extends boolean = false> (
  options: OpenFileOptions<T> = {}
): Promise<T extends true ? string[] : string | null> {
  const {
    title = 'Open File',
    startPath = process.cwd(),
    filterPatterns = ['*'],
    filterPatternsDescription = 'all files',
    allowMultipleSelects = false
  } = options

  let files: string[]
  switch (process.platform) {
    case 'darwin':
      files = await openFileMac(title, startPath, filterPatterns)
      break
    case 'win32':
      files = await openFileWindows(
        title,
        startPath,
        filterPatterns,
        filterPatternsDescription,
        allowMultipleSelects
      )
      break
    case 'linux':
      files = await openFileLinux(
        title,
        startPath,
        filterPatterns,
        filterPatternsDescription,
        allowMultipleSelects
      )
      break
    default:
      throw new Error(`Unsupported platform: ${process.platform}`)
  }

  return (allowMultipleSelects ? files : files[0] ?? null) as T extends true ? string[] : string | null
}

/**
 * Split entry lines outputted from a CLI util
 * @param output The CLI output
 * @returns      The lines
 */
function splitNonEmpty (output: string): string[] {
  return output
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
}

/**
 * Escape paths for Mac
 * @param str The string to escape
 * @returns   The escaped string
 */
function escapeAppleScript (str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

/**
 * Generate a type clause for Mac from types
 * @param filterPatterns The filters
 * @returns              The type clause
 */
function macTypeClause (filterPatterns: string[]): string {
  if (!filterPatterns.length || filterPatterns.includes('*')) return ''
  const exts = filterPatterns
    .map((p) => p.replace(/^\*\.?/, '').trim())
    .filter(Boolean)
    .map((e) => `"${e}"`)
  return exts.length ? `of type {${exts.join(', ')}} ` : ''
}

/**
 * Open a file on MacOS
 * @param title          The title of the dialog
 * @param startPath      The path to start in
 * @param filterPatterns The file types to filter for
 * @returns              The selected files
 */
async function openFileMac (
  title: string,
  startPath: string,
  filterPatterns: string[]
): Promise<string[]> {
  const script = `try
  set theFiles to choose file with prompt "${escapeAppleScript(title)}" default location (POSIX file "${escapeAppleScript(startPath)}") ${macTypeClause(filterPatterns)}with multiple selections allowed
  set posixPaths to {}
  repeat with aFile in theFiles
    set end of posixPaths to (POSIX path of aFile)
  end repeat
  set AppleScript's text item delimiters to linefeed
  return posixPaths as text
on error
  return ""
end try
`

  const scriptPath = path.resolve(os.tmpdir(), 'dialog.applescript')
  await fs.writeFile(scriptPath, script, 'utf8')
  const proc = Bun.spawn({ cmd: ['osascript', scriptPath], windowsHide: true })
  await proc.exited
  return splitNonEmpty(await new Response(proc.stdout).text())
}

/**
 * Construct a Windows file type filter
 * @param filterPatterns The filter patterns
 * @param description    The description of the types
 * @returns              The filter
 */
function windowsFilter (filterPatterns: string[], description: string): string {
  const noFilter = !filterPatterns.length || filterPatterns.includes('*')
  const patterns = noFilter
    ? ['*.*']
    : filterPatterns.map((p) =>
      p.startsWith('*') ? p : `*.${p.replace(/^\./, '')}`
    )
  return `${description}|${patterns.join(';')}`
}

const POWERSHELL_SCRIPT = `param(
  [string]$Title,
  [string]$InitialDirectory,
  [string]$Filter,
  [string]$Multiselect = "False"
)
Add-Type -AssemblyName System.Windows.Forms
$dialog = New-Object System.Windows.Forms.OpenFileDialog
$dialog.Title = $Title
$dialog.InitialDirectory = $InitialDirectory
$dialog.Filter = $Filter
$dialog.Multiselect = ($Multiselect -eq "True")
$dialog.RestoreDirectory = $true
if ($dialog.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {
  Write-Output ($dialog.FileNames -join "\`n")
}
`

/**
 * Open a file dialog for Windows
 * @param title                     The title of the window
 * @param startPath                 The starting directory
 * @param filterPatterns            The file type filters
 * @param filterPatternsDescription A description of the file types
 * @param allowMultipleSelects      Allow multiple files to be selected
 * @returns                         The paths to the files
 */
async function openFileWindows (
  title: string,
  startPath: string,
  filterPatterns: string[],
  filterPatternsDescription: string,
  allowMultipleSelects: boolean
): Promise<string[]> {
  const scriptPath = path.resolve(os.tmpdir(), 'dialog.ps1')
  await fs.writeFile(scriptPath, POWERSHELL_SCRIPT, 'utf8')
  const proc = Bun.spawn({
    cmd: [
      'powershell',
      '-NoProfile',
      '-NonInteractive',
      '-ExecutionPolicy',
      'Bypass',
      '-File',
      scriptPath,
      '-Title',
      title,
      '-InitialDirectory',
      startPath,
      '-Filter',
      windowsFilter(filterPatterns, filterPatternsDescription),
      '-Multiselect',
      allowMultipleSelects ? 'True' : 'False'
    ],
    windowsHide: true
  })
  await proc.exited
  return splitNonEmpty(await new Response(proc.stdout).text())
}

/**
 * Construct filter arguments for Zenity
 * @param filterPatterns The filter patterns
 * @param description    The description of the file types
 * @returns              The arguments
 */
function zenityFilterArg (
  filterPatterns: string[],
  description: string
): string | null {
  if (!filterPatterns.length || filterPatterns.includes('*')) return null
  const patterns = filterPatterns.map((p) =>
    p.startsWith('*') ? p : `*.${p.replace(/^\./, '')}`
  )
  return `--file-filter=${description} | ${patterns.join(' ')}`
}

/**
 * Use Zenity to select a file
 * @param title          The title of the dialog
 * @param startPath      The path to start in
 * @param filterPatterns The file types to filter on
 * @param description    A description of the file types
 * @param multiple       Whether to allow multiple files to be selected or not
 * @returns              The paths to the selected files
 */
async function runZenity (
  title: string,
  startPath: string,
  filterPatterns: string[],
  description: string,
  multiple: boolean
): Promise<string[]> {
  const args = [
    '--file-selection',
    `--title=${title}`,
    `--filename=${startPath.endsWith('/') ? startPath : startPath + '/'}`
  ]
  const filterArg = zenityFilterArg(filterPatterns, description)
  if (filterArg) args.push(filterArg)
  if (multiple) args.push('--multiple', '--separator=\n')

  const proc = Bun.spawn({ cmd: ['zenity', ...args], windowsHide: true })
  await proc.exited
  return splitNonEmpty(await new Response(proc.stdout).text())
}

/**
 * Construct filter args for kdialog
 * @param filterPatterns The filter patterns
 * @param description    The description of the file types
 * @returns              The arguments
 */
function kdialogFilter (filterPatterns: string[], description: string): string {
  if (!filterPatterns.length || filterPatterns.includes('*')) { return `*|${description}` }
  const patterns = filterPatterns.map((p) =>
    p.startsWith('*') ? p : `*.${p.replace(/^\./, '')}`
  )
  return `${patterns.join(' ')}|${description}`
}

/**
 * Use kdialog to select a file
 * @param title          The title of the dialog
 * @param startPath      The path to start in
 * @param filterPatterns The filter patterns
 * @param description    The description of the file types
 * @param multiple       Whether to allow selecting multiple files
 * @returns              The paths of the selected files
 */
async function runKdialog (
  title: string,
  startPath: string,
  filterPatterns: string[],
  description: string,
  multiple: boolean
): Promise<string[]> {
  const args = [
    '--getopenfilename',
    startPath,
    kdialogFilter(filterPatterns, description),
    '--title',
    title
  ]
  if (multiple) args.push('--multiple', '--separator', '\n')

  const proc = Bun.spawn({ cmd: ['kdialog', ...args], windowsHide: true })
  await proc.exited
  return splitNonEmpty(await new Response(proc.stdout).text())
}

/**
 * Open a file dialog for Linux
 * @param title                     The title of the dialog
 * @param startPath                 The path to start in
 * @param filterPatterns            The filter patterns
 * @param filterPatternsDescription The ddescription of the filter patterns
 * @param allowMultipleSelects      Whether to allow multiple files to be selected
 * @returns                         The paths to the selected files
 */
async function openFileLinux (
  title: string,
  startPath: string,
  filterPatterns: string[],
  filterPatternsDescription: string,
  allowMultipleSelects: boolean
): Promise<string[]> {
  try {
    return await runZenity(
      title,
      startPath,
      filterPatterns,
      filterPatternsDescription,
      allowMultipleSelects
    )
  } catch (err: any) {
    if (err?.code !== 'ENOENT') throw err
  }
  try {
    return await runKdialog(
      title,
      startPath,
      filterPatterns,
      filterPatternsDescription,
      allowMultipleSelects
    )
  } catch (err: any) {
    if (err?.code === 'ENOENT') {
      throw new Error(
        'No file dialog tool found. Install one with: sudo apt install zenity (most distros) or sudo apt install kdialog (KDE).'
      )
    }
    throw err
  }
}
